package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Banquete generated by hbm2java
 */
public class Banquete implements java.io.Serializable {

	private Integer baquetePk;
	private String nombre;
	private String borrado;
	private Date fechaAlta;
	private Date fechaBaja;
	private int usuarioFk;

	public Banquete() {
	}

	public Banquete(String nombre, String borrado, Date fechaAlta, Date fechaBaja, int usuarioFk) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.usuarioFk = usuarioFk;
	}

	public Integer getBaquetePk() {
		return this.baquetePk;
	}

	public void setBaquetePk(Integer baquetePk) {
		this.baquetePk = baquetePk;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public int getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(int usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

}
