package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * CatTipoPlato generated by hbm2java
 */
public class CatTipoPlato implements java.io.Serializable {

	private Integer tipoPlatoPk;
	private String nombre;
	private Date fechaAlta;
	private Date fechaBaja;
	private String borrado;
	private int usuarioFk;

	public CatTipoPlato() {
	}

	public CatTipoPlato(String nombre, Date fechaAlta, String borrado, int usuarioFk) {
		this.nombre = nombre;
		this.fechaAlta = fechaAlta;
		this.borrado = borrado;
		this.usuarioFk = usuarioFk;
	}

	public CatTipoPlato(String nombre, Date fechaAlta, Date fechaBaja, String borrado, int usuarioFk) {
		this.nombre = nombre;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.borrado = borrado;
		this.usuarioFk = usuarioFk;
	}

	public Integer getTipoPlatoPk() {
		return this.tipoPlatoPk;
	}

	public void setTipoPlatoPk(Integer tipoPlatoPk) {
		this.tipoPlatoPk = tipoPlatoPk;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public int getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(int usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

}
