package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Coctel generated by hbm2java
 */
public class Coctel implements java.io.Serializable {

	private Integer coctelPk;
	private int nombre;
	private String borrado;
	private Date fechaAlta;
	private Date fechaBaja;
	private int usuarioFk;
	private int comensales;

	public Coctel() {
	}

	public Coctel(int nombre, String borrado, Date fechaAlta, Date fechaBaja, int usuarioFk, int comensales) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.usuarioFk = usuarioFk;
		this.comensales = comensales;
	}

	public Integer getCoctelPk() {
		return this.coctelPk;
	}

	public void setCoctelPk(Integer coctelPk) {
		this.coctelPk = coctelPk;
	}

	public int getNombre() {
		return this.nombre;
	}

	public void setNombre(int nombre) {
		this.nombre = nombre;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public int getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(int usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

	public int getComensales() {
		return this.comensales;
	}

	public void setComensales(int comensales) {
		this.comensales = comensales;
	}

}
