package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private Integer eventoPk;
	private String nombre;
	private String borrado;
	private Date fechaAlta;
	private Date fechaBaja;
	private Integer usuarioFk;
	private int comensales;
	private String observaciones;
	private String encargado;
	private Integer recenaFk;
	private Integer coctelFk;
	private Integer banqueteFk;

	public Evento() {
	}

	public Evento(String nombre, String borrado, Date fechaAlta, int comensales, String observaciones,
			String encargado) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.comensales = comensales;
		this.observaciones = observaciones;
		this.encargado = encargado;
	}

	public Evento(String nombre, String borrado, Date fechaAlta, Date fechaBaja, Integer usuarioFk, int comensales,
			String observaciones, String encargado, Integer recenaFk, Integer coctelFk, Integer banqueteFk) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.usuarioFk = usuarioFk;
		this.comensales = comensales;
		this.observaciones = observaciones;
		this.encargado = encargado;
		this.recenaFk = recenaFk;
		this.coctelFk = coctelFk;
		this.banqueteFk = banqueteFk;
	}

	public Integer getEventoPk() {
		return this.eventoPk;
	}

	public void setEventoPk(Integer eventoPk) {
		this.eventoPk = eventoPk;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public Integer getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(Integer usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

	public int getComensales() {
		return this.comensales;
	}

	public void setComensales(int comensales) {
		this.comensales = comensales;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getEncargado() {
		return this.encargado;
	}

	public void setEncargado(String encargado) {
		this.encargado = encargado;
	}

	public Integer getRecenaFk() {
		return this.recenaFk;
	}

	public void setRecenaFk(Integer recenaFk) {
		this.recenaFk = recenaFk;
	}

	public Integer getCoctelFk() {
		return this.coctelFk;
	}

	public void setCoctelFk(Integer coctelFk) {
		this.coctelFk = coctelFk;
	}

	public Integer getBanqueteFk() {
		return this.banqueteFk;
	}

	public void setBanqueteFk(Integer banqueteFk) {
		this.banqueteFk = banqueteFk;
	}

}
