package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ingredientes generated by hbm2java
 */
public class Ingredientes implements java.io.Serializable {

	private Integer ingredientesPk;
	private String nombre;
	private String borrado;
	private Date fechaAlta;
	private Date fechaBaja;
	private int usuarioFk;
	private Integer alergenosFk;
	private Integer nutrientesFk;
	private Set relacionPlatosIngredienteses = new HashSet(0);

	public Ingredientes() {
	}

	public Ingredientes(String nombre, String borrado, Date fechaAlta, int usuarioFk) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.usuarioFk = usuarioFk;
	}

	public Ingredientes(String nombre, String borrado, Date fechaAlta, Date fechaBaja, int usuarioFk,
			Integer alergenosFk, Integer nutrientesFk, Set relacionPlatosIngredienteses) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.usuarioFk = usuarioFk;
		this.alergenosFk = alergenosFk;
		this.nutrientesFk = nutrientesFk;
		this.relacionPlatosIngredienteses = relacionPlatosIngredienteses;
	}

	public Integer getIngredientesPk() {
		return this.ingredientesPk;
	}

	public void setIngredientesPk(Integer ingredientesPk) {
		this.ingredientesPk = ingredientesPk;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public int getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(int usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

	public Integer getAlergenosFk() {
		return this.alergenosFk;
	}

	public void setAlergenosFk(Integer alergenosFk) {
		this.alergenosFk = alergenosFk;
	}

	public Integer getNutrientesFk() {
		return this.nutrientesFk;
	}

	public void setNutrientesFk(Integer nutrientesFk) {
		this.nutrientesFk = nutrientesFk;
	}

	public Set getRelacionPlatosIngredienteses() {
		return this.relacionPlatosIngredienteses;
	}

	public void setRelacionPlatosIngredienteses(Set relacionPlatosIngredienteses) {
		this.relacionPlatosIngredienteses = relacionPlatosIngredienteses;
	}

}
