package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Puestos generated by hbm2java
 */
public class Puestos implements java.io.Serializable {

	private Integer puestoPk;
	private String nombre;
	private String borrado;
	private Date fechaAlta;
	private Date fechaBaja;
	private int usuarioFk;
	private int tipoPuestoFk;
	private int comensales;

	public Puestos() {
	}

	public Puestos(String nombre, String borrado, Date fechaAlta, Date fechaBaja, int usuarioFk, int tipoPuestoFk,
			int comensales) {
		this.nombre = nombre;
		this.borrado = borrado;
		this.fechaAlta = fechaAlta;
		this.fechaBaja = fechaBaja;
		this.usuarioFk = usuarioFk;
		this.tipoPuestoFk = tipoPuestoFk;
		this.comensales = comensales;
	}

	public Integer getPuestoPk() {
		return this.puestoPk;
	}

	public void setPuestoPk(Integer puestoPk) {
		this.puestoPk = puestoPk;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getBorrado() {
		return this.borrado;
	}

	public void setBorrado(String borrado) {
		this.borrado = borrado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public int getUsuarioFk() {
		return this.usuarioFk;
	}

	public void setUsuarioFk(int usuarioFk) {
		this.usuarioFk = usuarioFk;
	}

	public int getTipoPuestoFk() {
		return this.tipoPuestoFk;
	}

	public void setTipoPuestoFk(int tipoPuestoFk) {
		this.tipoPuestoFk = tipoPuestoFk;
	}

	public int getComensales() {
		return this.comensales;
	}

	public void setComensales(int comensales) {
		this.comensales = comensales;
	}

}
