package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

/**
 * RelacionPuestosPlat generated by hbm2java
 */
public class RelacionPuestosPlat implements java.io.Serializable {

	private Integer puestosPlatPk;
	private int puestosFk;
	private int platosFk;

	public RelacionPuestosPlat() {
	}

	public RelacionPuestosPlat(int puestosFk, int platosFk) {
		this.puestosFk = puestosFk;
		this.platosFk = platosFk;
	}

	public Integer getPuestosPlatPk() {
		return this.puestosPlatPk;
	}

	public void setPuestosPlatPk(Integer puestosPlatPk) {
		this.puestosPlatPk = puestosPlatPk;
	}

	public int getPuestosFk() {
		return this.puestosFk;
	}

	public void setPuestosFk(int puestosFk) {
		this.puestosFk = puestosFk;
	}

	public int getPlatosFk() {
		return this.platosFk;
	}

	public void setPlatosFk(int platosFk) {
		this.platosFk = platosFk;
	}

}
