package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

/**
 * RelacionPlatosIngredientes generated by hbm2java
 */
public class RelacionPlatosIngredientes implements java.io.Serializable {

	private Integer platIngPk;
	private Ingredientes ingredientes;
	private Platos platos;

	public RelacionPlatosIngredientes() {
	}

	public RelacionPlatosIngredientes(Ingredientes ingredientes, Platos platos) {
		this.ingredientes = ingredientes;
		this.platos = platos;
	}

	public Integer getPlatIngPk() {
		return this.platIngPk;
	}

	public void setPlatIngPk(Integer platIngPk) {
		this.platIngPk = platIngPk;
	}

	public Ingredientes getIngredientes() {
		return this.ingredientes;
	}

	public void setIngredientes(Ingredientes ingredientes) {
		this.ingredientes = ingredientes;
	}

	public Platos getPlatos() {
		return this.platos;
	}

	public void setPlatos(Platos platos) {
		this.platos = platos;
	}

}
