package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

/**
 * RelacionBanquetePlat generated by hbm2java
 */
public class RelacionBanquetePlat implements java.io.Serializable {

	private Integer banquetePlatPk;
	private int banqueteFk;
	private int platosFk;

	public RelacionBanquetePlat() {
	}

	public RelacionBanquetePlat(int banqueteFk, int platosFk) {
		this.banqueteFk = banqueteFk;
		this.platosFk = platosFk;
	}

	public Integer getBanquetePlatPk() {
		return this.banquetePlatPk;
	}

	public void setBanquetePlatPk(Integer banquetePlatPk) {
		this.banquetePlatPk = banquetePlatPk;
	}

	public int getBanqueteFk() {
		return this.banqueteFk;
	}

	public void setBanqueteFk(int banqueteFk) {
		this.banqueteFk = banqueteFk;
	}

	public int getPlatosFk() {
		return this.platosFk;
	}

	public void setPlatosFk(int platosFk) {
		this.platosFk = platosFk;
	}

}
