package beans.model;
// Generated 01-dic-2018 11:35:44 by Hibernate Tools 5.3.6.Final

/**
 * RelacionRecenaPuestos generated by hbm2java
 */
public class RelacionRecenaPuestos implements java.io.Serializable {

	private Integer recenaPuestosPk;
	private int recenaFk;
	private int puestosFk;

	public RelacionRecenaPuestos() {
	}

	public RelacionRecenaPuestos(int recenaFk, int puestosFk) {
		this.recenaFk = recenaFk;
		this.puestosFk = puestosFk;
	}

	public Integer getRecenaPuestosPk() {
		return this.recenaPuestosPk;
	}

	public void setRecenaPuestosPk(Integer recenaPuestosPk) {
		this.recenaPuestosPk = recenaPuestosPk;
	}

	public int getRecenaFk() {
		return this.recenaFk;
	}

	public void setRecenaFk(int recenaFk) {
		this.recenaFk = recenaFk;
	}

	public int getPuestosFk() {
		return this.puestosFk;
	}

	public void setPuestosFk(int puestosFk) {
		this.puestosFk = puestosFk;
	}

}
